public class PolicyException extends Exception {
    private int ID;

    public PolicyException(int ID) {
        this.ID = ID;
    }

    public int getID() {
        return ID;
    }

    @Override
    public String toString() {
        return UserInterface.BOLD + 
        " The Policy ID was not valid and a new ID (" + ID + ") is generated by admin and assigned for the Policy"+
        UserInterface.RESET;
    }
}